#!/usr/bin/env python3
"""生成crawl_v2_engine.py"""
lines = []
lines.append('import httpx,re,json,time,random,os,sys')
lines.append('from typing import Optional')
lines.append('sys.path.insert(0,os.path.dirname(os.path.abspath(__file__)))')
lines.append('from storage.db import AppInfoDB')
lines.append('from utils.logger import setup_logger,get_logger')
lines.append('setup_logger()')
lines.append('L=get_logger("direct_crawler")')
lines.append('from crawl_v2 import KNOWN')
lines.append('')
lines.append('def _fetch(client, pkg, rq):')
lines.append('    url=f"https://sj.qq.com/appdetail/{pkg}"')
lines.append('    try:')
lines.append('        r=client.get(url)')
lines.append('        if r.status_code!=200 or len(r.text)<2000: return None')
lines.append('        info={"package_name":pkg,"url":url}')
lines.append('        m=re.search(r\'<script id="__NEXT_DATA__"[^>]*>(.*?)</script>\',r.text,re.DOTALL)')
lines.append('        if m:')
lines.append('            try:')
lines.append('                nd=json.loads(m.group(1))')
lines.append('                pp=nd.get("props",{}).get("pageProps",{})')
lines.append('                dcr=pp.get("dynamicCardResponse",{}).get("data",{})')
lines.append('                if isinstance(dcr,dict):')
lines.append('                    for comp in dcr.get("components",[]):')
lines.append('                        cd=comp.get("data",{})')
lines.append('                        if not isinstance(cd,dict): continue')
lines.append('                        if cd.get("name")=="GameDetail":')
lines.append('                            items=cd.get("itemData",[])')
lines.append('                            if isinstance(items,str): items=json.loads(items)')
lines.append('                            if isinstance(items,list) and items:')
lines.append('                                it=items[0]')
lines.append('                                for k,ik in [("app_name","name"),("developer","developer"),("version","version_name"),("enterprise_name","operator")]:')
lines.append('                                    if it.get(ik): info[k]=it[ik]')
lines.append('                                if it.get("download_num"): info["download_count"]=str(it["download_num"])')
lines.append('                                if it.get("description"): info["description"]=str(it["description"])[:500]')
lines.append('                        if cd.get("name") in ("YouMayAlsoLike","SameDeveloper"):')
lines.append('                            its=cd.get("itemData",[])')
lines.append('                            if isinstance(its,str): its=json.loads(its)')
lines.append('                            if isinstance(its,list):')
lines.append('                                for x in its:')
lines.append('                                    if isinstance(x,dict) and x.get("pkg_name"): rq.append(x["pkg_name"])')
lines.append('                seo=pp.get("seoMeta",{})')
lines.append('                if not info.get("app_name") and seo.get("title"): info["app_name"]=_ptitle(seo["title"])')
lines.append('                if not info.get("description") and seo.get("description"): info["description"]=seo["description"][:500]')
lines.append('            except Exception: pass')
lines.append('        if not info.get("app_name"):')
lines.append('            from bs4 import BeautifulSoup')
lines.append('            soup=BeautifulSoup(r.text,"lxml")')
lines.append('            t=soup.select_one("title")')
lines.append('            if t:')
lines.append('                tt=t.get_text(strip=True)')
lines.append('                if len(tt)<5 or "\\u627e\\u4e0d\\u5230" in tt or "404" in tt: return None')
lines.append('                info["app_name"]=_ptitle(tt)')
lines.append('        return info if info.get("app_name") else None')
lines.append('    except Exception: return None')
lines.append('')
lines.append('def _ptitle(title):')
lines.append('    if not title: return None')
lines.append('    n=re.sub(r"-\\u5e94\\u7528\\u5b9d.*$","",title).strip()')
lines.append('    if "-" in n: n=n.split("-")[0].strip()')
lines.append('    n=re.sub(r"(app|APP|App).*$","",n).strip()')
lines.append('    n=re.sub(r"(\\u5b98\\u65b9|\\u5b98\\u7f51|\\u514d\\u8d39|\\u6700\\u65b0|\\u4e0b\\u8f7d|\\u5b89\\u88c5|\\u6b63\\u7248|\\u7248\\u672c).*$","",n).strip()')
lines.append('    return n if n and len(n)>=1 and "\\u5e94\\u7528\\u5b9d" not in n else None')
lines.append('')
lines.append('def _gpl(pkg,name):')
lines.append('    p=pkg.lower(); n=(name or"").lower()')
lines.append('    if "tencent" in p: return "\\u4f01\\u4e1a\\u5fae\\u4fe1"')
lines.append('    if any(k in p for k in ["alibaba","taobao","alipay","rimet","autonavi","youku","cainiao","tmall","ucmobile"]): return "\\u9489\\u9489"')
lines.append('    if any(k in p for k in ["ss.android","bytedance","lark","luna.music"]): return "\\u98de\\u4e66"')
lines.append('    if "\\u4f01\\u4e1a\\u5fae\\u4fe1" in n or "wework" in n: return "\\u4f01\\u4e1a\\u5fae\\u4fe1"')
lines.append('    if "\\u9489\\u9489" in n or "dingtalk" in n: return "\\u9489\\u9489"')
lines.append('    if "\\u98de\\u4e66" in n or "lark" in n: return "\\u98de\\u4e66"')
lines.append('    if "cn.gov" in p or "\\u653f\\u52a1" in n: return "\\u653f\\u52a1\\u670d\\u52a1"')
lines.append('    return "\\u529e\\u516c\\u534f\\u540c"')
lines.append('')
lines.append('def _save(db,info,found):')
lines.append('    pkg=info.get("package_name",""); name=info.get("app_name",""); pl=info.get("product_line","\\u529e\\u516c\\u534f\\u540c")')
lines.append('    if not pkg or not name or pkg in found: return False')
lines.append('    try:')
lines.append('        ok=db.insert_app(package_name=pkg,app_name=name,product_line=pl,enterprise_name=info.get("enterprise_name",""),developer=info.get("developer",""),version=info.get("version",""),version_code="",update_date="",download_count=info.get("download_count",""),description=info.get("description",""),source_site="\\u5e94\\u7528\\u5b9d",source_url=info.get("url",""),discovery_method="yingyongbao_v2")')
lines.append('        if ok:')
lines.append('            found.add(pkg)')
lines.append('            L.info(f"  + {pkg:40s} | {name[:20]:20s} | {pl}")')
lines.append('        return ok')
lines.append('    except Exception: return False')
lines.append('')
lines.append('def run_all():')
lines.append('    db=AppInfoDB()')
lines.append('    client=httpx.Client(timeout=20,follow_redirects=True,verify=False,headers={"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","Accept-Language":"zh-CN,zh;q=0.9"})')
lines.append('    found=set(); checked=set(); rq=[]; nk=ns=0')
lines.append('    try: c=db._get_conn(); c.execute("DELETE FROM app_info"); c.commit()')
lines.append('    except: pass')
lines.append('    L.info(f"v2\\u722c\\u866b, {len(KNOWN)}\\u4e2a\\u5df2\\u77e5\\u5305\\u540d")')
lines.append('    L.info("--- \\u9636\\u6bb51 ---")')
lines.append('    for i,(pkg,pl) in enumerate(KNOWN):')
lines.append('        if pkg in checked: continue')
lines.append('        if i%20==0 and i>0: L.info(f"  {i}/{len(KNOWN)}, +{nk}")')
lines.append('        info=_fetch(client,pkg,rq)')
lines.append('        if info:')
lines.append('            info["product_line"]=pl')
lines.append('            if _save(db,info,found): nk+=1')
lines.append('        checked.add(pkg)')
lines.append('        time.sleep(random.uniform(0.15,0.4))')
lines.append('    L.info(f"\\u96361: {nk}/{len(KNOWN)}")')
lines.append('    L.info("--- \\u9636\\u6bb52 ---")')
lines.append('    for rnd in range(1,4):')
lines.append('        batch=list(set(rq)); rq.clear()')
lines.append('        new=[p for p in batch if p not in checked]')
lines.append('        if not new: break')
lines.append('        L.info(f"  \\u8f6e{rnd}: {len(new)}\\u4e2a")')
lines.append('        rf=0')
lines.append('        for i,pkg in enumerate(new):')
lines.append('            if pkg in checked: continue')
lines.append('            if i%30==0 and i>0: L.info(f"    {i}/{len(new)}, +{rf}")')
lines.append('            info=_fetch(client,pkg,rq)')
lines.append('            if info:')
lines.append('                info["product_line"]=_gpl(pkg,info.get("app_name",""))')
lines.append('                if _save(db,info,found): ns+=1; rf+=1')
lines.append('            checked.add(pkg)')
lines.append('            time.sleep(random.uniform(0.15,0.4))')
lines.append('        L.info(f"  \\u8f6e{rnd}: +{rf}, \\u603b{len(found)}")')
lines.append('    total=db.count()')
lines.append('    L.info(f"\\u5b8c\\u6210! \\u603b{total}, \\u5df2\\u77e5{nk}, \\u6eda\\u96ea\\u7403{ns}")')
lines.append('    if total>0:')
lines.append('        L.info("\\u5bfc\\u51fa...")')
lines.append('        from storage.db import CustomerDB')
lines.append('        from storage.exporter import DataExporter')
lines.append('        from pipeline.quality_scorer import QualityScorer')
lines.append('        QualityScorer(db).run()')
lines.append('        cdb=CustomerDB()')
lines.append('        exp=DataExporter(cdb,db)')
lines.append('        for nm,pa in exp.export_all().items(): L.info(f"  {nm} -> {pa}")')
lines.append('        exp.print_summary()')
lines.append('        cdb.close()')
lines.append('    client.close(); db.close()')
lines.append('    return total')

with open('/data/workspace/Myprogram/pacong/crawl_v2_engine.py', 'w') as f:
    # Write header
    f.write('import httpx,re,json,time,random,os,sys\n')
    f.write('from typing import Optional\n')
    f.write('sys.path.insert(0,os.path.dirname(os.path.abspath(__file__)))\n')
    f.write('from storage.db import AppInfoDB\n')
    f.write('from utils.logger import setup_logger,get_logger\n')
    f.write('setup_logger()\n')
    f.write('L=get_logger("direct_crawler")\n')
    f.write('from crawl_v2 import KNOWN\n')
    # Write all function lines
    for line in lines:
        f.write(line + '\n')

print(f"Generated crawl_v2_engine.py with {len(lines)+8} lines")
