"""已知应用包名列表"""
# 格式: (包名, 预估产品线, 备注)
KNOWN_APPS = [
    # 腾讯系 -> 企业微信
    ('com.tencent.wework','企业微信','企业微信'),
    ('com.tencent.docs','企业微信','腾讯文档'),
    ('com.tencent.tim','企业微信','TIM'),
    ('com.tencent.mobileqq','企业微信','QQ'),
    ('com.tencent.mm','企业微信','微信'),
    ('com.tencent.qqmail','企业微信','QQ邮箱'),
    ('com.tencent.map','企业微信','腾讯地图'),
    ('com.tencent.qqlive','企业微信','腾讯视频'),
    ('com.tencent.qqmusic','企业微信','QQ音乐'),
    ('com.tencent.karaoke','企业微信','全民K歌'),
    ('com.tencent.weishi','企业微信','微视'),
    ('com.tencent.news','企业微信','腾讯新闻'),
    ('com.tencent.mtt','企业微信','QQ浏览器'),
    ('com.tencent.androidqqmanager','企业微信','手机管家'),
    ('com.tencent.wetype','企业微信','微信输入法'),
    ('com.tencent.reading','企业微信','QQ阅读'),
    # 阿里系 -> 钉钉
    ('com.alibaba.android.rimet','钉钉','钉钉'),
    ('com.alibaba.aliyun','钉钉','阿里云'),
    ('com.taobao.taobao','钉钉','淘宝'),
    ('com.eg.android.AlipayGphone','钉钉','支付宝'),
    ('com.taobao.idlefish','钉钉','闲鱼'),
    ('com.alibaba.wireless.ichangmessenger','钉钉','千牛'),
    ('com.tmall.wireless','钉钉','天猫'),
    ('com.UCMobile','钉钉','UC浏览器'),
    ('com.autonavi.minimap','钉钉','高德地图'),
    ('com.youku.phone','钉钉','优酷'),
    ('com.taobao.trip','钉钉','飞猪'),
    ('com.cainiao.wireless.homepage','钉钉','菜鸟'),
    ('com.alibaba.teambition','钉钉','Teambition'),
    # 字节系 -> 飞书
    ('com.ss.android.lark','飞书','飞书'),
    ('com.ss.android.article.news','飞书','今日头条'),
    ('com.ss.android.ugc.aweme','飞书','抖音'),
    ('com.ss.android.ugc.aweme.lite','飞书','抖音极速版'),
    ('com.ss.android.article.lite','飞书','头条极速版'),
    ('com.ss.android.ugc.live','飞书','抖音火山版'),
    ('com.ss.android.auto','飞书','懂车帝'),
    ('com.ss.android.article.video','飞书','西瓜视频'),
    ('com.luna.music','飞书','汽水音乐'),
    # 办公协同
    ('cn.wps.moffice_eng','办公协同','WPS'),
    ('cn.wps.yun','办公协同','WPS云'),
    ('com.huawei.welink','办公协同','WeLink'),
    ('com.seeyon.cmp','办公协同','致远M3'),
    ('com.weaver.emobile7','办公协同','泛微'),
    ('com.inspur.emmcloud','办公协同','浪潮'),
    ('com.microsoft.teams','办公协同','Teams'),
    ('com.microsoft.office.outlook','办公协同','Outlook'),
    ('com.microsoft.skydrive','办公协同','OneDrive'),
    ('com.microsoft.office.word','办公协同','Word'),
    ('com.microsoft.office.excel','办公协同','Excel'),
    ('com.microsoft.office.powerpoint','办公协同','PPT'),
    ('com.microsoft.office.onenote','办公协同','OneNote'),
    # 银行/金融
    ('com.icbc','办公协同','工商银行'),
    ('com.chinamworld.bocmbci','办公协同','中国银行'),
    ('com.ecitic.bank.mobile','办公协同','中信银行'),
    ('cmb.pb','办公协同','招商银行'),
    ('com.chinamworld.main','办公协同','建设银行'),
    ('com.android.bankabc','办公协同','农业银行'),
    ('com.bankcomm.Bankcomm','办公协同','交通银行'),
    ('com.pingan.papd','办公协同','平安金管家'),
    ('com.yitong.mbank.psbc','办公协同','邮储银行'),
    ('com.spdb.mobilebankN','办公协同','浦发银行'),
    ('com.cib.cibmb','办公协同','兴业银行'),
    # 通讯/邮箱
    ('com.netease.mail','办公协同','网易邮箱'),
    # 招聘
    ('com.zhaopin.social','办公协同','智联招聘'),
    ('com.nowcoder.app.florida','办公协同','牛客'),
    ('com.hpbr.bosszhipin','办公协同','BOSS直聘'),
    # 笔记/网盘
    ('com.yinxiang','办公协同','印象笔记'),
    ('com.youdao.note','办公协同','有道云笔记'),
    ('com.baidu.netdisk','办公协同','百度网盘'),
    # 政务
    ('com.hanweb.android.zhejiang.activity','政务服务','浙里办'),
    # 社交/媒体
    ('com.sina.weibo','办公协同','微博'),
    ('com.zhihu.android','办公协同','知乎'),
    ('tv.danmaku.bili','办公协同','B站'),
    ('com.xingin.xhs','办公协同','小红书'),
    # 百度系
    ('com.baidu.searchbox','办公协同','百度'),
    ('com.baidu.BaiduMap','办公协同','百度地图'),
    ('com.baidu.input','办公协同','百度输入法'),
    ('com.iflytek.inputmethod','办公协同','讯飞输入法'),
    # 出行
    ('com.sdu.didi.psnger','办公协同','滴滴'),
    ('ctrip.android.view','办公协同','携程'),
    ('com.MobileTicket','办公协同','12306'),
    # 网易系
    ('com.netease.cloudmusic','办公协同','网易云音乐'),
    ('com.netease.newsreader.activity','办公协同','网易新闻'),
    # 快手
    ('com.kuaishou.nebula','办公协同','快手'),
    # 电商
    ('com.jingdong.app.mall','办公协同','京东'),
    ('com.xunmeng.pinduoduo','办公协同','拼多多'),
    ('com.meituan','办公协同','美团'),
    ('com.dianping.v1','办公协同','大众点评'),
    ('com.sankuai.meituan.takeoutnew','办公协同','美团外卖'),
    # 视频/娱乐
    ('com.qiyi.video','办公协同','爱奇艺'),
    ('com.kugou.android','办公协同','酷狗'),
    ('com.ximalaya.ting.android','办公协同','喜马拉雅'),
    ('com.hunantv.imgo.activity','办公协同','芒果TV'),
    # 效率/工具
    ('com.todesk','办公协同','ToDesk'),
    ('com.oray.sunlogin','办公协同','向日葵'),
    ('com.youdao.dict','办公协同','有道词典'),
    ('com.camscanner.online','办公协同','扫描全能王'),
    ('com.baidu.translate','办公协同','百度翻译'),
    # 金融
    ('com.eastmoney.android.berlin','办公协同','东方财富'),
    ('com.hexin.plat.android','办公协同','同花顺'),
    ('com.chinaums.pmp','办公协同','云闪付'),
    # 物流
    ('com.sf.activity','办公协同','顺丰'),
    # 其他
    ('com.xunlei.downloadprovider','办公协同','迅雷'),
    ('com.cubic.autohome','办公协同','汽车之家'),
    ('com.tongcheng.android','办公协同','同程旅行'),
    ('com.fenbi.android.servant','办公协同','粉笔'),
    ('com.chaoxing.mobile','办公协同','学习通'),
    ('us.zoom.videomeetings','办公协同','Zoom'),
    ('com.gotokeep.keep','办公协同','Keep'),
    ('com.suning.mobile.ebuy','办公协同','苏宁'),
]
